Scouterna/Jamboree21

wiki/.azure-pipelines/build.yaml
=> Fix build pipeline: Working directory :D

wiki/.azure-pipelines/build.yaml, wiki/.k8s/mediawiki.yaml
This is getting ridiculous, apparently there are no limits to the little bugs I can introduce to this project. 
1. `sed` doesn't understand when there's a space between a flag and its argument.
2. When using `sed` to replace a string with another string (`%IMAGE%` with the url of a container image) it works much better if the string exists in the first place.
=> Fix build AGAIN

wiki/simplesamlconfig/config.php
Jag uppdaterade hemligheterna nu, och lo and behold det hjälpte - vi kom ett steg längre! Dock var Microsoft sura på att vi bad om att bli tillbakaskickade till en annan adress än vi kom ifrån, nämligen exakt samma adress men http istället för https... Låt oss se hur det här går.
=> Make it known to SSP that we use https

wiki/.k8s/mediawiki.yaml
This reverts commit 4a06f5dff69d11088b0700e0c2b7cc4f654dc5d0.
=> Revert "Use ScoutID"

wiki/LocalSettings.php
...I'm quite sure this change should accomplish that and make the logs available in Grafana
=> Send wiki debug logs to Loki

wiki/LocalSettings.php
Extend the search from #27, to also include users.
=> Allow to also seach for users

facelist/.k8s/deployment.yaml
=> Add deployment selector

wiki/LocalSettings.php
Jag hittar inget sätt att få till ett regex-filter, så jag tar och byter namn på alla befintliga användare istället #kulkväll :D
=> Revert "wiki: Lowercase all usernames"

charts/minecraft/build.yaml
=> minecraft: helm upgrade should use values file

charts/minecraft/templates/30-deployment-local.yaml
=> Minecraft: make it as beefy as possible

.azure-pipelines/templates/tag-build.step.yaml, facelist/.azure-pipelines/build.yaml, facelist/.azure-pipelines/container-image-tags.sh, facelist/.k8s/cronjob.yaml, facelist/.k8s/deployment.yaml
- facelist: fix YAML indentation
- facelist: fix volumeMount capitalization
- facelist: fix build script
- facelist: make build script more readable
- facelist: fix aboutme data path
- facelist: only build downloader when it's changed
- build: only tag builds of master branch
- facelist: push k8s artifact after replacing image placeholder
- facelist: always publish k8s artifact
- facelist: move container image paths to script file
=> facelist fixes

wikiupdate_api/.k8s/deployment.yaml
=> give container a name

wikiupdate_api/sendhook.py
- wikibot: Set time to 11:45 CET
- wikiapi: fix sleep timeout
=> Fix time zone difference

charts/wiki/templates/deployment.yaml, charts/wiki/templates/pvc.yaml, charts/wiki/values/production.yaml
- wiki: Add disk storage for images
- wiki: Increase image storage size
=> images to disk

charts/wiki/templates/ingress.yaml, charts/wiki/values/dev.yaml, charts/wiki/values/production.yaml
- wiki: Add secondary hostname wiki.jamboree.se
- wiki: fix chart issues
=> wiki.jamboree.se

charts/wiki/templates/configmap.yaml
- wiki: fix domain values in charts
- wiki: parantheses in chart template
=> fix domains

charts/wiki/Chart.yaml, charts/wiki/templates/configmap.yaml
=> wiki: add appVersion

charts/planera/templates/ingress.yaml, charts/template/templates/ingress.yaml, charts/wiki/templates/ingress.yaml, charts/wsj2023-access/templates/ingress.yaml
=> charts: Update annotation namespaces

wikiupdate_api/sendhook.py
So we don't post the same thing a billion times
=> feat: filter everything older than 30 minutes

wikiupdate_api/sendhook.py
=> fix: actually don't send empty updates

wsj2023-access/application/main.py, wsj2023-access/client/src/App.svelte, wsj2023-access/client/src/StatusBoolean.svelte, wsj2023-access/client/src/StatusNumber.svelte
Change-Id: If1bb85c3bd00c69ef28f623b24d7793eeb35b770
=> [WSJ] Update wsj

charts/scoutwise/templates/service.yaml, scoutwise/api/app.py
Change-Id: I59071f14a2b32bb9d1d19d34bf679b014a7065c8
=> Fix service

wiki/Dockerfile, wiki/LocalSettings.php, wiki/composer.local.json, wiki/composer.local.lock
* Update semantic mediawiki to version 4
* Fix composer install (use root composer.json that includes our composer.local.json, don't refer directly to composer.local.json)
=>  wiki: Fix upgrade to MW 1.36.4

charts/wiki/templates/ingress.yaml, wsj2023-access/.gitignore, wsj2023-access/application/main.py
Change-Id: Ic79effcb15b6ee5754818ccd2fd5bf868cbafca2
=> Fix questions in app

wsj2023-access/application/main.py, wsj2023-access/application/script/fetch_json.py, wsj2023-access/client/src/Participants.js
Change-Id: I0c21ae2c2604c3c36fed92e1b12d63c0996cfc08
=> Check in/out participants
